from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import VendorViewSet, PurchaseOrderViewSet

# Create a DefaultRouter to handle URL routing for the viewsets
router = DefaultRouter()

# Register the VendorViewSet with the 'vendors' endpoint
router.register(r'vendors', VendorViewSet, basename='vendor')

# Register the PurchaseOrderViewSet with the 'purchase_orders' endpoint
router.register(r'purchase_orders', PurchaseOrderViewSet, basename='purchase_order')

# Define the urlpatterns to include the routes generated by the DefaultRouter
urlpatterns = [
    # Include the generated URL patterns from the router
    path('', include(router.urls)),
]
